on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
      - main
      - master
name: Semgrep

jobs:
  buildmavenDepTree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Generate dependency tree
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt -DoutputType=text

      - name: Upload Dependency Tree Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mavendeptree
          path: maven_dep_tree.txt

  semgrep:
    needs: buildmavenDepTree
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: mavendeptree

      - name: Run Semgrep supply-chain scan and fail on critical/high
        run: |
          semgrep ci | tee scan_output.txt
          if grep -E "CRITICAL|HIGH" scan_output.txt; then
            echo "Critical/high vulnerability found! Failing the job."
            exit 1
          else
            echo "No critical/high vulnerabilities found."
          fi
